name: Compilar bitzero.py para 64 bits

on:
  push:
    paths:
      - 'bitzero.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev gcc-aarch64-linux-gnu
          pip3 install cython setuptools
      
      - name: Compilar para 64 bits
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CFLAGS="-O3 -march=armv8-a -mtune=cortex-a53 -fomit-frame-pointer -flto -ffast-math"
          cythonize -3 -b bitzero.py
          aarch64-linux-gnu-gcc -O3 -march=armv8-a -shared -fPIC \
            -I/usr/include/python3.10 \
            -o bitzero_64.so bitzero.c
      
      - name: Subir binario 64-bit
        uses: actions/upload-artifact@v4
        with:
          name: bitzero_64.bin
          path: bitzero_64.so
